apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-spring-app-kube-deployment
  labels:
    app: simple-spring-app-kube
#    app.kubernetes.io/name: simple-spring-app
#    app.kubernetes.io/component: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-spring-app-kube
  template:
    metadata:
      labels:
        app: simple-spring-app-kube
    spec:
      containers:
        - name: simple-spring-app-kube
          image: gcr.io/gcp-simple-spring-microservice/spring-app-jenkins:2.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http

#          env:
#            - name: DATABASE_URL
#              value: postgresql://postgres:gYwOKJZaR0do8TUUgPS9@pg:5432/postgres