apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-spring-app
  labels:
    app: simple-spring-app-kube
spec:
  rules:
#    - host: ktswebinar.ktsdev.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: simple-spring-app-kube
                port:
                  name: http