apiVersion: v1
kind: Service
metadata:
  name: simple-spring-app
  labels:
    app.kubernetes.io/name: simple-spring-app
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: simple-spring-app
    app.kubernetes.io/component: web
