apiVersion: v1
kind: Service
metadata:
  name: simple-spring-app-service
  labels:
    app: simple-spring-app-kube
#    app.kubernetes.io/name: simple-spring-app
#    app.kubernetes.io/component: web
spec:
  type: LoadBalancer
  selector:
    app:
      app: simple-spring-app-kube
#    app.kubernetes.io/name: simple-spring-app
#    app.kubernetes.io/component: web
  ports:
    - protocol: TCP
      port: 8080
      name: http
      targetPort: http



