apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-spring-app
  labels:
    app.kubernetes.io/name: simple-spring-app
    app.kubernetes.io/component: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: simple-spring-app
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: simple-spring-app
        app.kubernetes.io/component: web
    spec:
      containers:
        - name: simple-spring-app
          image: gcr.io/gcp-simple-spring-microservice/simple-spring-app-kube:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
#          env:
#            - name: DATABASE_URL
#              value: postgresql://postgres:gYwOKJZaR0do8TUUgPS9@pg:5432/postgres