apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app-jenkins
  labels:
    app.kubernetes.io/name: spring-app-jenkins
    app.kubernetes.io/component: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: spring-app-jenkins
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spring-app-jenkins
        app.kubernetes.io/component: web
    spec:
      containers:
        - name: spring-app-jenkins
          image: gcr.io/gcp-simple-spring-microservice/spring-app-jenkins:2.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
      imagePullSecrets:
        - name: reg-secret

#          env:
#            - name: DATABASE_URL
#              value: postgresql://postgres:gYwOKJZaR0do8TUUgPS9@pg:5432/postgres