apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-spring-app-kube-deployment
  labels:
    app: spring-app-jenkins
#    app.kubernetes.io/name: simple-spring-app
#    app.kubernetes.io/component: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-app-jenkins
  #      app.kubernetes.io/name: simple-spring-app
  #      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app: spring-app-jenkins
    #        app.kubernetes.io/name: simple-spring-app
    #        app.kubernetes.io/component: web
    spec:
      containers:
        - name: spring-app-jenkins
          image: https://gcr.io/gcp-simple-spring-microservice/spring-app-jenkins:2.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
#          env:
#            - name: DATABASE_URL
#              value: postgresql://postgres:gYwOKJZaR0do8TUUgPS9@pg:5432/postgres